nama= input("masukkan nama...")
NIM= input("masukkan NIM...")
Kelas=input("masukkan Kelas...")
Matkul=input("masukkan Matkul...")
jam=input("masukkan Jam...")
print(nama)
print(NIM)
print(Kelas)
print(Matkul)
print(jam)
